### ISSUE TITLE
Extend the GUI Testing coverage

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#174]
In GitLab by @mariusalexander on Dec 15, 2021, 09:13

The GUI Testing System should use submodules and additoonal GUI Tests should be implemented.

## Improve GUI Testing System
- [x] Improve stability of GUI Tests (eg. ~~multiple pipelines running at once~~ waiting for other instances) #178 
- [x] Use submodules for the GUI Tests

## Implement more gui tests
  - [x] Test the `GtShortCutEdit` - #171
  - [x] Tasks should be skippable - #82 #176
  - [x] Zooming in on a `GtGrid` should no longer result in a crash - #179
