### ISSUE TITLE
Replace remaining old icons using svgs

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#442]
In GitLab by @mariusalexander on Feb 21, 2023, 08:42

There are still some icons that should be revisited and some old icons that should be replaced:

### TODO:
- [x] letters
- [x] combuster, compressor, turbine icon (currently placeholder for empty object icon)
- [x] create icons for file types (like stepFile, HDF5-File)
- [ ] Find icon for Python
- [x] missing Map icons
- [x] missing Schedules icons
- [x] add function for collection icon
- [ ] icon for performance model
