### ISSUE TITLE
Prepare OpenSource: Meta issue for our Open Source strategy

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#497]
In GitLab by @rainman110 on Mar 27, 2023, 07:13

 - [ ] Define License
 - [ ] cmake build / remove qmake
 - [ ] Standardize installed file structure (no .so files in bin under linux)
 - [ ] Doxygen Documentation target
 - [ ] Integrate GTlabLogging and GenH5 into cmake build to reduce build-time dependencies
 - [ ] Create conan packages in CI (for Logging, GenH5, Core)
 - [ ] Decide, which modules to bundle with GTlab

# License

We want a free license that require the user to use the name GTlab for derived work

 - LGPL (could allow dual licensing for commercial use)
 - MIT
 - BSD
 - Apache
