### ISSUE TITLE
Resolve "Fix bug in dynamic type registration in meta object system" - [merged]

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#814]
In GitLab by @real-ct-ac on Jun 27, 2022, 11:43

_Merges 248-fix-bug-in-dynamic-type-registration-in-meta-object-system -> master_

## Checklist:

- [x] A test for the new functionality was added (if applicable).
- [x] All tests run without failure.
- [x] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [x] The new code complies with the GTlab's style guide.
- [x] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [x] The number of code quality warnings is not increasing.

Closes #248
